/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import javax.swing.*;
import java.sql.*;
import java.util.*;
import java.time.*;
import java.time.format.*;
import javaapplication2.Model.*;

/**
 *
 * @author randy
 */
public class MainFrame extends javax.swing.JFrame {

    Koneksi dbsetting;
    String driver, database, user, password, nama_menu;
    Long harga_menu, id_menu;
    Object table;
    DefaultListModel listModel = new DefaultListModel<Menu>();
    String pesanan_id;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        dbsetting = new Koneksi();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        password = dbsetting.SettingPanel("DBPassword");
        settableload();
        MenuTable.setModel(MenuModel);
    }
    
    private void updateMenuTable(){
        MenuModel = getMenuTableModel();
        settableload();
        MenuTable.setModel(MenuModel);
    }
    
    private void updatePesananTable(){
        PesananModel = getPesananTableModel();
        setTablePesananLoad();
        PesananTable.setModel(PesananModel);
    }
    
    private void loadComboBoxMenuPesanan(){
        combo_box_menu_pesanan.removeAllItems();
        DefaultComboBoxModel combo = new DefaultComboBoxModel<Menu>();
        List<Menu> list_menu = Menu.all();
        for(Menu menu: list_menu){
            combo.addElement(menu);
        }
        combo_box_menu_pesanan.setModel(combo);
    }
    
    private void loadComboBoxPelangganPesanan(){
        combo_box_pelanggan_pesanan.removeAllItems();
        DefaultComboBoxModel combo = new DefaultComboBoxModel<Pelanggan>();
        List<Pelanggan> list_pelanggan = Pelanggan.all();
        for(Pelanggan pelanggan: list_pelanggan){
            combo.addElement(pelanggan);
        }
        combo_box_pelanggan_pesanan.setModel(combo);
    }
    private void loadListMenuPesanan(){
        list_menu_pesanan.removeAll();
        DefaultListModel<Menu> list_menu_model = new  DefaultListModel<Menu>();
        Pesanan pesanan = Pesanan.find(pesanan_id);
        List<Menu> list_menu = pesanan.list_menu();
        for(Menu menu: list_menu){
            list_menu_model.addElement(menu);
        }
        list_menu_pesanan.setModel(list_menu_model);
    }
    
    private int count(long row1, long row2, ResultSet res){
        int ct = 1;
        try{
            while(res.next()){
                if(row1 == res.getLong(1)){
                  if(row2 == res.getLong(4)){
                      ct += 1;
                  }
                }
            }
        }catch(Exception e){
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
        return ct;
    }
    private void setTablePesananLoad(){
        List<Pesanan> list_pesanan = Pesanan.all();
        for(Pesanan pesanan: list_pesanan){
            System.out.println(pesanan.toString());
            PesananModel.addRow(pesanan.toTableRow());
        }
    }
    private void setTablePelangganLoad(){
        String data[] = new String[3];
        String stat = "";
        try{
            PelangganModel = getPelangganTableModel();
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, password);
            Statement stt =  kon.createStatement();
            String SQL = "select * from pelanggan";
            ResultSet res = stt.executeQuery(SQL);
            while(res.next()){
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                data[2] = res.getString(3);
                PelangganModel.addRow(data);
            }
            res.close();
            stt.close();
            kon.close();
        }catch(Exception e){
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }
    private void setMenuTableCariLoad(String cari){
        List<Menu> list_menu = Menu.cari(cari);
        for(Menu menu: list_menu){
            MenuModel.addRow(menu.toTableRow());
        }
    }
    private void settableload(){
        List<Menu> list_menu = Menu.all();
        for(Menu menu: list_menu){
            MenuModel.addRow(menu.toTableRow());
        }
    }
    public void membersihkan_text()
    {
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_tambah_pesanan = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_field_qty_menu_pesanan = new javax.swing.JTextField();
        combo_box_menu_pesanan = new javax.swing.JComboBox<>();
        combo_box_pelanggan_pesanan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tambah_menu_pesanan = new javax.swing.JButton();
        tombol_simpan_menu_pesanan = new javax.swing.JButton();
        tombol_hapus_menu_pesanan = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        list_menu_pesanan = new javax.swing.JList<>();
        tombol_hapus_semua_menu_pesanan = new javax.swing.JButton();
        date_chooser_tambah_pesanan = new datechooser.beans.DateChooserCombo();
        frame_view_pesanan = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_menu_view_pesanan = new javax.swing.JList<>();
        text_field_pelanggan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tombol_tutup_view_pesanan = new javax.swing.JButton();
        text_field_subtotal_pesanan = new javax.swing.JTextField();
        frame_ubah_pesanan = new javax.swing.JFrame();
        tombol_hapus_semua_menu_pesanan_edit = new javax.swing.JButton();
        combo_box_pelanggan_pesanan_edit = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        list_menu_pesanan_edit = new javax.swing.JList<>();
        tombol_simpan_pesanan_edit = new javax.swing.JButton();
        combo_box_menu_pesanan_edit = new javax.swing.JComboBox<>();
        text_field_jumlah_menu_pesanan_edit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        date_chooser_pesanan_edit = new datechooser.beans.DateChooserCombo();
        jLabel9 = new javax.swing.JLabel();
        tombol_tambah_menu_pesanan_edit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tombol_hapus_menu_pesanan_edit = new javax.swing.JButton();
        dialog_pesanan_status = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        tombol_ya_dialog_status_pesanan = new javax.swing.JButton();
        tombol_tidak_dialog_status_pesanan = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JTabbedPane();
        MenuPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MenuTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        text_field_cari = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        text_field_nama = new javax.swing.JTextField();
        text_field_harga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PelangganPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PelangganTable = new javax.swing.JTable();
        PesananPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PesananTable = new javax.swing.JTable();
        text_field_cari_pesanan = new javax.swing.JTextField();
        tombol_cari_pesanan = new javax.swing.JButton();
        tombol_show_frame_tambah_pesanan = new javax.swing.JButton();
        tombol_ubah_pesanan = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        tombol_status_pesanan = new javax.swing.JButton();

        frame_tambah_pesanan.setSize(new java.awt.Dimension(600, 360));
        frame_tambah_pesanan.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                frame_tambah_pesananComponentShown(evt);
            }
        });

        jLabel3.setText("Pelanggan");

        jLabel4.setText("Menu");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tambah Pesanan");

        text_field_qty_menu_pesanan.setText("1");
        text_field_qty_menu_pesanan.setMinimumSize(new java.awt.Dimension(100, 22));
        text_field_qty_menu_pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_qty_menu_pesananActionPerformed(evt);
            }
        });

        jLabel6.setText("Qty");

        tambah_menu_pesanan.setText("Tambah");
        tambah_menu_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah_menu_pesananMouseClicked(evt);
            }
        });

        tombol_simpan_menu_pesanan.setText("Simpan");
        tombol_simpan_menu_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombol_simpan_menu_pesananMouseClicked(evt);
            }
        });
        tombol_simpan_menu_pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_simpan_menu_pesananActionPerformed(evt);
            }
        });

        tombol_hapus_menu_pesanan.setText("Hapus");
        tombol_hapus_menu_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombol_hapus_menu_pesananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombol_hapus_menu_pesananMouseEntered(evt);
            }
        });
        tombol_hapus_menu_pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_hapus_menu_pesananActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(list_menu_pesanan);

        tombol_hapus_semua_menu_pesanan.setText("Hapus Semua");
        tombol_hapus_semua_menu_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombol_hapus_semua_menu_pesananMouseClicked(evt);
            }
        });

        date_chooser_tambah_pesanan.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));

    javax.swing.GroupLayout frame_tambah_pesananLayout = new javax.swing.GroupLayout(frame_tambah_pesanan.getContentPane());
    frame_tambah_pesanan.getContentPane().setLayout(frame_tambah_pesananLayout);
    frame_tambah_pesananLayout.setHorizontalGroup(
        frame_tambah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(frame_tambah_pesananLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(frame_tambah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(frame_tambah_pesananLayout.createSequentialGroup()
                    .addGroup(frame_tambah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(combo_box_pelanggan_pesanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_tambah_pesananLayout.createSequentialGroup()
                            .addComponent(combo_box_menu_pesanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(frame_tambah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(text_field_qty_menu_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_tambah_pesananLayout.createSequentialGroup()
                            .addGroup(frame_tambah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frame_tambah_pesananLayout.createSequentialGroup()
                                    .addComponent(tambah_menu_pesanan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                    .addComponent(tombol_hapus_menu_pesanan))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frame_tambah_pesananLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(12, 12, 12)
                            .addComponent(tombol_hapus_semua_menu_pesanan))
                        .addGroup(frame_tambah_pesananLayout.createSequentialGroup()
                            .addGroup(frame_tambah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(frame_tambah_pesananLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(date_chooser_tambah_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(frame_tambah_pesananLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tombol_simpan_menu_pesanan)))
            .addContainerGap())
    );
    frame_tambah_pesananLayout.setVerticalGroup(
        frame_tambah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_tambah_pesananLayout.createSequentialGroup()
            .addGroup(frame_tambah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frame_tambah_pesananLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel5)
                    .addGap(33, 33, 33)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(combo_box_pelanggan_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addGroup(frame_tambah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(frame_tambah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_field_qty_menu_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combo_box_menu_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                    .addComponent(date_chooser_tambah_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(frame_tambah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tombol_hapus_menu_pesanan)
                        .addComponent(tambah_menu_pesanan)
                        .addComponent(tombol_hapus_semua_menu_pesanan)))
                .addGroup(frame_tambah_pesananLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5)))
            .addGap(18, 18, 18)
            .addComponent(tombol_simpan_menu_pesanan)
            .addContainerGap())
    );

    frame_view_pesanan.setSize(new java.awt.Dimension(500, 360));
    frame_view_pesanan.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentShown(java.awt.event.ComponentEvent evt) {
            frame_view_pesananComponentShown(evt);
        }
    });

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel7.setText("Info Pesanan");

    jScrollPane4.setViewportView(list_menu_view_pesanan);

    text_field_pelanggan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            text_field_pelangganActionPerformed(evt);
        }
    });

    jLabel8.setText("Pelanggan");

    tombol_tutup_view_pesanan.setText("Tutup");

    javax.swing.GroupLayout frame_view_pesananLayout = new javax.swing.GroupLayout(frame_view_pesanan.getContentPane());
    frame_view_pesanan.getContentPane().setLayout(frame_view_pesananLayout);
    frame_view_pesananLayout.setHorizontalGroup(
        frame_view_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(frame_view_pesananLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(frame_view_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frame_view_pesananLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tombol_tutup_view_pesanan))
                .addGroup(frame_view_pesananLayout.createSequentialGroup()
                    .addGroup(frame_view_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(frame_view_pesananLayout.createSequentialGroup()
                            .addGroup(frame_view_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text_field_pelanggan, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(frame_view_pesananLayout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(27, 27, 27))
                        .addGroup(frame_view_pesananLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)))
                    .addGroup(frame_view_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(text_field_subtotal_pesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
            .addContainerGap())
    );
    frame_view_pesananLayout.setVerticalGroup(
        frame_view_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(frame_view_pesananLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(frame_view_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frame_view_pesananLayout.createSequentialGroup()
                    .addComponent(jLabel7)
                    .addGap(49, 49, 49)
                    .addComponent(jLabel8)
                    .addGap(8, 8, 8)
                    .addComponent(text_field_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, Short.MAX_VALUE)
            .addComponent(text_field_subtotal_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(tombol_tutup_view_pesanan)
            .addGap(20, 20, 20))
    );

    frame_ubah_pesanan.setMinimumSize(new java.awt.Dimension(600, 400));
    frame_ubah_pesanan.setSize(new java.awt.Dimension(600, 400));
    frame_ubah_pesanan.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentShown(java.awt.event.ComponentEvent evt) {
            frame_ubah_pesananComponentShown(evt);
        }
    });

    tombol_hapus_semua_menu_pesanan_edit.setText("Hapus Semua");
    tombol_hapus_semua_menu_pesanan_edit.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tombol_hapus_semua_menu_pesanan_editMouseClicked(evt);
        }
    });

    jLabel11.setText("Menu");

    jScrollPane7.setViewportView(list_menu_pesanan_edit);

    tombol_simpan_pesanan_edit.setText("Simpan");
    tombol_simpan_pesanan_edit.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tombol_simpan_pesanan_editMouseClicked(evt);
        }
    });

    text_field_jumlah_menu_pesanan_edit.setText("1");
    text_field_jumlah_menu_pesanan_edit.setMinimumSize(new java.awt.Dimension(58, 22));

    jLabel12.setText("Qty");

    jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel9.setText("Ubah Pesanan");

    tombol_tambah_menu_pesanan_edit.setText("Tambah");
    tombol_tambah_menu_pesanan_edit.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tombol_tambah_menu_pesanan_editMouseClicked(evt);
        }
    });

    jLabel10.setText("Pelanggan");

    tombol_hapus_menu_pesanan_edit.setText("Hapus");
    tombol_hapus_menu_pesanan_edit.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tombol_hapus_menu_pesanan_editMouseClicked(evt);
        }
    });

    javax.swing.GroupLayout frame_ubah_pesananLayout = new javax.swing.GroupLayout(frame_ubah_pesanan.getContentPane());
    frame_ubah_pesanan.getContentPane().setLayout(frame_ubah_pesananLayout);
    frame_ubah_pesananLayout.setHorizontalGroup(
        frame_ubah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(frame_ubah_pesananLayout.createSequentialGroup()
            .addGroup(frame_ubah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_ubah_pesananLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(frame_ubah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(frame_ubah_pesananLayout.createSequentialGroup()
                            .addComponent(tombol_tambah_menu_pesanan_edit)
                            .addGap(18, 18, 18)
                            .addComponent(tombol_hapus_menu_pesanan_edit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tombol_hapus_semua_menu_pesanan_edit))
                        .addGroup(frame_ubah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(date_chooser_pesanan_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frame_ubah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(combo_box_pelanggan_pesanan_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(frame_ubah_pesananLayout.createSequentialGroup()
                                    .addGroup(frame_ubah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(combo_box_menu_pesanan_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(frame_ubah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(text_field_jumlah_menu_pesanan_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_ubah_pesananLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombol_simpan_pesanan_edit)))
            .addContainerGap())
    );
    frame_ubah_pesananLayout.setVerticalGroup(
        frame_ubah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(frame_ubah_pesananLayout.createSequentialGroup()
            .addGroup(frame_ubah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frame_ubah_pesananLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jLabel9)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(combo_box_pelanggan_pesanan_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(frame_ubah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(frame_ubah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combo_box_menu_pesanan_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(text_field_jumlah_menu_pesanan_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(date_chooser_pesanan_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(68, 68, 68)
                    .addGroup(frame_ubah_pesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tombol_tambah_menu_pesanan_edit)
                        .addComponent(tombol_hapus_menu_pesanan_edit)
                        .addComponent(tombol_hapus_semua_menu_pesanan_edit)))
                .addGroup(frame_ubah_pesananLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
            .addComponent(tombol_simpan_pesanan_edit)
            .addContainerGap())
    );

    dialog_pesanan_status.setMinimumSize(new java.awt.Dimension(600, 360));

    jLabel15.setText("Tekan ya untuk menyelesaikan pesanan");

    tombol_ya_dialog_status_pesanan.setText("Ya");
    tombol_ya_dialog_status_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tombol_ya_dialog_status_pesananMouseClicked(evt);
        }
    });

    tombol_tidak_dialog_status_pesanan.setText("Tidak");
    tombol_tidak_dialog_status_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tombol_tidak_dialog_status_pesananMouseClicked(evt);
        }
    });

    jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel13.setText("Selesaikan Pesanan?");

    jLabel14.setText("Pesanan yang telah selesai tidak dapat diubah dan dihapus. ");

    javax.swing.GroupLayout dialog_pesanan_statusLayout = new javax.swing.GroupLayout(dialog_pesanan_status.getContentPane());
    dialog_pesanan_status.getContentPane().setLayout(dialog_pesanan_statusLayout);
    dialog_pesanan_statusLayout.setHorizontalGroup(
        dialog_pesanan_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(dialog_pesanan_statusLayout.createSequentialGroup()
            .addContainerGap(21, Short.MAX_VALUE)
            .addGroup(dialog_pesanan_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_pesanan_statusLayout.createSequentialGroup()
                    .addComponent(jLabel15)
                    .addGap(90, 90, 90))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_pesanan_statusLayout.createSequentialGroup()
                    .addGroup(dialog_pesanan_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dialog_pesanan_statusLayout.createSequentialGroup()
                            .addComponent(tombol_ya_dialog_status_pesanan)
                            .addGap(167, 167, 167)
                            .addComponent(tombol_tidak_dialog_status_pesanan))
                        .addComponent(jLabel14))
                    .addGap(20, 20, 20))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_pesanan_statusLayout.createSequentialGroup()
                    .addComponent(jLabel13)
                    .addGap(88, 88, 88))))
    );
    dialog_pesanan_statusLayout.setVerticalGroup(
        dialog_pesanan_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_pesanan_statusLayout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addComponent(jLabel13)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel14)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel15)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
            .addGroup(dialog_pesanan_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tombol_tidak_dialog_status_pesanan)
                .addComponent(tombol_ya_dialog_status_pesanan))
            .addGap(48, 48, 48))
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    MainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            MainPanelMouseClicked(evt);
        }
    });

    MenuTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    MenuTable.setMinimumSize(MenuPanel.getMinimumSize());
    MenuTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            MenuTableMouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(MenuTable);

    jButton1.setText("Tambah");
    jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jButton1MouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            jButton1MouseEntered(evt);
        }
    });
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setText("Ubah");
    jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jButton2MouseClicked(evt);
        }
    });
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    jButton3.setText("Hapus");
    jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jButton3MouseClicked(evt);
        }
    });
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    text_field_cari.setText("Cari nama");
    text_field_cari.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            text_field_cariActionPerformed(evt);
        }
    });

    jButton5.setText("Cari");
    jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jButton5MouseClicked(evt);
        }
    });

    text_field_nama.setText("Masukan Nama");
    text_field_nama.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            text_field_namaActionPerformed(evt);
        }
    });

    text_field_harga.setText("Masukan Harga");
    text_field_harga.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            text_field_hargaActionPerformed(evt);
        }
    });

    jLabel1.setText("Nama");

    jLabel2.setText("Harga");

    javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
    MenuPanel.setLayout(MenuPanelLayout);
    MenuPanelLayout.setHorizontalGroup(
        MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        .addGroup(MenuPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MenuPanelLayout.createSequentialGroup()
                    .addComponent(text_field_cari)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton5))
                .addGroup(MenuPanelLayout.createSequentialGroup()
                    .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(text_field_nama)
                        .addComponent(text_field_harga)))
                .addGroup(MenuPanelLayout.createSequentialGroup()
                    .addComponent(jButton1)
                    .addGap(18, 18, 18)
                    .addComponent(jButton2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3)))
            .addContainerGap())
    );
    MenuPanelLayout.setVerticalGroup(
        MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(MenuPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(text_field_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton5))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(text_field_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
            .addGap(10, 10, 10)
            .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(text_field_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jButton2)
                .addComponent(jButton3))
            .addContainerGap(72, Short.MAX_VALUE))
    );

    MainPanel.addTab("Menu", MenuPanel);

    PelangganPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentShown(java.awt.event.ComponentEvent evt) {
            PelangganPanelComponentShown(evt);
        }
    });

    PelangganTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    jScrollPane1.setViewportView(PelangganTable);

    javax.swing.GroupLayout PelangganPanelLayout = new javax.swing.GroupLayout(PelangganPanel);
    PelangganPanel.setLayout(PelangganPanelLayout);
    PelangganPanelLayout.setHorizontalGroup(
        PelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
    );
    PelangganPanelLayout.setVerticalGroup(
        PelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PelangganPanelLayout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    MainPanel.addTab("Pelanggan", PelangganPanel);

    PesananPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentShown(java.awt.event.ComponentEvent evt) {
            PesananPanelComponentShown(evt);
        }
    });

    PesananTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    PesananTable.setSurrendersFocusOnKeystroke(true);
    PesananTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            PesananTableMouseClicked(evt);
        }
        public void mousePressed(java.awt.event.MouseEvent evt) {
            PesananTableMousePressed(evt);
        }
    });
    PesananTable.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentShown(java.awt.event.ComponentEvent evt) {
            PesananTableComponentShown(evt);
        }
    });
    jScrollPane3.setViewportView(PesananTable);

    text_field_cari_pesanan.setText("Cari pesanan");

    tombol_cari_pesanan.setText("Cari");
    tombol_cari_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tombol_cari_pesananMouseClicked(evt);
        }
    });
    tombol_cari_pesanan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tombol_cari_pesananActionPerformed(evt);
        }
    });

    tombol_show_frame_tambah_pesanan.setText("Tambah");
    tombol_show_frame_tambah_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tombol_show_frame_tambah_pesananMouseClicked(evt);
        }
    });

    tombol_ubah_pesanan.setText("Ubah");
    tombol_ubah_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tombol_ubah_pesananMouseClicked(evt);
        }
    });

    jButton8.setText("Hapus");
    jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jButton8MouseClicked(evt);
        }
    });
    jButton8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton8ActionPerformed(evt);
        }
    });

    tombol_status_pesanan.setText("Tandai Selesai");
    tombol_status_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tombol_status_pesananMouseClicked(evt);
        }
    });
    tombol_status_pesanan.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentShown(java.awt.event.ComponentEvent evt) {
            tombol_status_pesananComponentShown(evt);
        }
    });
    tombol_status_pesanan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tombol_status_pesananActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout PesananPanelLayout = new javax.swing.GroupLayout(PesananPanel);
    PesananPanel.setLayout(PesananPanelLayout);
    PesananPanelLayout.setHorizontalGroup(
        PesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(PesananPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(PesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addGroup(PesananPanelLayout.createSequentialGroup()
                    .addComponent(tombol_show_frame_tambah_pesanan)
                    .addGap(18, 18, 18)
                    .addComponent(tombol_ubah_pesanan)
                    .addGap(18, 18, 18)
                    .addComponent(tombol_status_pesanan)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8))
                .addGroup(PesananPanelLayout.createSequentialGroup()
                    .addComponent(text_field_cari_pesanan)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tombol_cari_pesanan)))
            .addContainerGap())
    );
    PesananPanelLayout.setVerticalGroup(
        PesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(PesananPanelLayout.createSequentialGroup()
            .addGap(11, 11, 11)
            .addGroup(PesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(text_field_cari_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tombol_cari_pesanan))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(PesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tombol_show_frame_tambah_pesanan)
                .addComponent(tombol_ubah_pesanan)
                .addComponent(jButton8)
                .addComponent(tombol_status_pesanan))
            .addContainerGap(145, Short.MAX_VALUE))
    );

    MainPanel.addTab("Pesanan", PesananPanel);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(MainPanel)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(MainPanel)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainPanelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MainPanelMouseClicked

    private void PelangganPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PelangganPanelComponentShown
        // TODO add your handling code here:
        setTablePelangganLoad();
        PelangganTable.setModel(PelangganModel);
    }//GEN-LAST:event_PelangganPanelComponentShown

    private void PesananPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PesananPanelComponentShown
        // TODO add your handling code here:
        updatePesananTable();
    }//GEN-LAST:event_PesananPanelComponentShown

    private void text_field_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_namaActionPerformed

    private void text_field_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_hargaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        try
//        {
//            Class.forName(database);
//            Connection kon = DriverManager.getConnection(database,user,pass);
//            Statement stt = kon.createStatement();
//            String SQL = "Delete from [nama table] * "+"where"+"nim='"+tableModel.getValueAt(row,0).toString()+"'";
//            stt.execute(SQL);
//            tableModel.removeRow(row);
//            stt.close;
//            kon.close;
//            membersihkan_text;
//        }
//        catch(Exception e){
//            System.err.println(e.getMessage());
//            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
//            System.exit(0);
//        }
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void text_field_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_cariActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        String cari = text_field_cari.getText();
        MenuModel = getMenuTableModel();
        setMenuTableCariLoad(cari);
        MenuTable.setModel(MenuModel);
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        [class();]
//        [nim].requestFocus();
//        btn_simpan.setEnabled(true);
//        btn_ubah.setEnabled(false);
//        btn_hapus.setEnabled(false);
//        btn_keluar.setEnabled(false);
//        aktif_teks();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String nama = text_field_nama.getText();
        String harga = text_field_harga.getText();
        Menu.create(nama, harga);
        updateMenuTable();
    }//GEN-LAST:event_jButton1MouseClicked

    private void MenuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTableMouseClicked
        // TODO add your handling code here:
        id_menu = Long.parseLong(MenuTable.getValueAt(MenuTable.getSelectedRow(), 0).toString());
        nama_menu = MenuTable.getValueAt(MenuTable.getSelectedRow(), 1).toString();
        harga_menu = Long.parseLong(MenuTable.getValueAt(MenuTable.getSelectedRow(), 2).toString());
        text_field_nama.setText(nama_menu);
        text_field_harga.setText(harga_menu.toString());
    }//GEN-LAST:event_MenuTableMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String nama = text_field_nama.getText();
        String harga = text_field_harga.getText();
        
        Menu menu = Menu.find(String.valueOf(id_menu));
        menu.update(nama, harga);
            
        updateMenuTable();
            
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Menu menu = Menu.find(String.valueOf(id_menu));
        menu.delete();
        updateMenuTable();
    }//GEN-LAST:event_jButton3MouseClicked

    private void PesananTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesananTableMouseClicked
        // TODO add your handling code here:
        pesanan_id = PesananTable.getModel().getValueAt(PesananTable.getSelectedRow(), 0).toString();
        System.err.println(pesanan_id);
        
    }//GEN-LAST:event_PesananTableMouseClicked

    private void PesananTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PesananTableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_PesananTableComponentShown

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tombol_show_frame_tambah_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_show_frame_tambah_pesananMouseClicked
        // TODO add your handling code here:
        frame_tambah_pesanan.setVisible(true);
    }//GEN-LAST:event_tombol_show_frame_tambah_pesananMouseClicked

    private void text_field_qty_menu_pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_qty_menu_pesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_qty_menu_pesananActionPerformed

    private void tombol_simpan_menu_pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_simpan_menu_pesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombol_simpan_menu_pesananActionPerformed

    private void tombol_hapus_menu_pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_hapus_menu_pesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombol_hapus_menu_pesananActionPerformed

    private void frame_tambah_pesananComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_frame_tambah_pesananComponentShown
        // TODO add your handling code here:
        loadComboBoxPelangganPesanan();
        loadComboBoxMenuPesanan();
        list_menu_pesanan.removeAll();
        listModel = new DefaultListModel<Menu>();
        list_menu_pesanan.setModel(listModel);
    }//GEN-LAST:event_frame_tambah_pesananComponentShown

    private void tambah_menu_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_menu_pesananMouseClicked
        // TODO add your handling code here:
        Object menu = combo_box_menu_pesanan.getSelectedItem();
        String menu_id = ((Menu)menu).getId();
        String menu_nama = ((Menu) menu).getNama();
        String menu_harga = ((Menu) menu).getHarga();
        String menu_qty = text_field_qty_menu_pesanan.getText();
        listModel.addElement(new Menu(menu_id, menu_nama, menu_harga, menu_qty));
        list_menu_pesanan.setModel(listModel);
    }//GEN-LAST:event_tambah_menu_pesananMouseClicked

    private void tombol_hapus_menu_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_hapus_menu_pesananMouseClicked
        // TODO add your handling code here:
        DefaultListModel ListModel = (DefaultListModel) list_menu_pesanan.getModel();
        if(list_menu_pesanan.getSelectedIndices().length > 0){
            int[] selected_indexes = list_menu_pesanan.getSelectedIndices();
            for (int index = selected_indexes.length-1; index >=0; index--) {
                ListModel.removeElementAt(index);
            }
        }
        list_menu_pesanan.setModel(ListModel);
    }//GEN-LAST:event_tombol_hapus_menu_pesananMouseClicked

    private void tombol_hapus_semua_menu_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_hapus_semua_menu_pesananMouseClicked
        // TODO add your handling code here:
        listModel = new DefaultListModel<Menu>();
        list_menu_pesanan.setModel(listModel);
    }//GEN-LAST:event_tombol_hapus_semua_menu_pesananMouseClicked

    private void tombol_simpan_menu_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_simpan_menu_pesananMouseClicked
        // TODO add your handling code here:
        Object pelanggan = combo_box_pelanggan_pesanan.getSelectedItem();
        String pelanggan_id = ((Pelanggan) pelanggan).getId();
        List<Menu> list_menu = new ArrayList<Menu>();
        String dateString = date_chooser_tambah_pesanan.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("M/d/yy");
        LocalDate localDate = LocalDate.parse(dateString, formatter);
        System.out.println("Created At : "+localDate.toString());
        
        for(int i = 0; i< list_menu_pesanan.getModel().getSize();i++){
            Object item = list_menu_pesanan.getModel().getElementAt(i);
            list_menu.add(((Menu) item));
        }
        
        Pesanan.create(pelanggan_id, list_menu, localDate.toString());
        
        updatePesananTable();

        frame_tambah_pesanan.setVisible(false);
        
    }//GEN-LAST:event_tombol_simpan_menu_pesananMouseClicked

    private void text_field_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_pelangganActionPerformed

    private void PesananTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesananTableMousePressed
        // TODO add your handling code here:
        if(evt.getClickCount() == 2 && PesananTable.getSelectedRow() != -1){
            frame_view_pesanan.setVisible(true);
            String id = PesananTable.getModel().getValueAt(PesananTable.getSelectedRow(), 0).toString();
            pesanan_id = id;
            System.out.println("Pesanan ID " + pesanan_id);
        }
    }//GEN-LAST:event_PesananTableMousePressed

    private void frame_view_pesananComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_frame_view_pesananComponentShown
        // TODO add your handling code here:
        Pesanan pesanan = Pesanan.find(pesanan_id);
        List<Menu> list_menu = pesanan.list_menu();
        Pelanggan pelanggan = pesanan.pelanggan();
        
        DefaultListModel<Menu> listModel = new DefaultListModel<Menu>();
        
        for(Menu menu: list_menu){
            listModel.addElement(menu);
        }
        
        text_field_subtotal_pesanan.setText(pesanan.getSubtotal());
        text_field_pelanggan.setText(pelanggan.toString());
        
        list_menu_view_pesanan.setModel(listModel);
    }//GEN-LAST:event_frame_view_pesananComponentShown

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void tombol_status_pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_status_pesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombol_status_pesananActionPerformed

    private void tombol_cari_pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_cari_pesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombol_cari_pesananActionPerformed

    private void tombol_ubah_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_ubah_pesananMouseClicked
        // TODO add your handling code here:
        Pesanan pesanan = Pesanan.find(pesanan_id);
        if(pesanan.status != null && (pesanan.status).equalsIgnoreCase("selesai")){
            JOptionPane.showMessageDialog(null, "Pesanan selesai, tidak dapat diubah", "Info", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            frame_ubah_pesanan.setVisible(true);
        }
    }//GEN-LAST:event_tombol_ubah_pesananMouseClicked

    private void tombol_status_pesananComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tombol_status_pesananComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tombol_status_pesananComponentShown

    private void frame_ubah_pesananComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_frame_ubah_pesananComponentShown
        // TODO add your handling code here:
        Pesanan pesanan = Pesanan.find(pesanan_id);
        List<Pelanggan> list_pelanggan = Pelanggan.all();
        Pelanggan pelanggan = Pelanggan.find(pesanan.getPelangganId());
        List<Menu> list_menu = Menu.all();
        List<Menu> menu_pesanan = pesanan.list_menu();

        DefaultComboBoxModel combo = new DefaultComboBoxModel<Pelanggan>();
        for(Pelanggan pel: list_pelanggan){
            combo.addElement(pel);
        }
        combo.setSelectedItem(pelanggan);
        combo_box_pelanggan_pesanan_edit.setModel(combo);
        

        DefaultComboBoxModel comboMenu = new DefaultComboBoxModel<Menu>();
        for(Menu me: list_menu){
            comboMenu.addElement(me);
        }
        combo_box_menu_pesanan_edit.setModel(comboMenu);
        
        listModel = new DefaultListModel<Menu>();
        for(Menu me: menu_pesanan){
            listModel.addElement(me);
        }
        list_menu_pesanan_edit.setModel(listModel);
    }//GEN-LAST:event_frame_ubah_pesananComponentShown

    private void tombol_tambah_menu_pesanan_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_tambah_menu_pesanan_editMouseClicked
        // TODO add your handling code here:
        Object menu = combo_box_menu_pesanan_edit.getSelectedItem();
        String menu_id = ((Menu)menu).getId();
        String menu_nama = ((Menu) menu).getNama();
        String menu_harga = ((Menu) menu).getHarga();
        String menu_qty = text_field_jumlah_menu_pesanan_edit.getText();
        listModel.addElement(new Menu(menu_id, menu_nama, menu_harga, menu_qty));
        list_menu_pesanan.setModel(listModel);
    }//GEN-LAST:event_tombol_tambah_menu_pesanan_editMouseClicked

    private void tombol_hapus_menu_pesanan_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_hapus_menu_pesanan_editMouseClicked
        // TODO add your handling code here:
        DefaultListModel ListModel = (DefaultListModel) list_menu_pesanan_edit.getModel();
        if(list_menu_pesanan_edit.getSelectedIndices().length > 0){
            int[] selected_indexes = list_menu_pesanan_edit.getSelectedIndices();
            for (int index = selected_indexes.length-1; index >=0; index--) {
                ListModel.removeElementAt(index);
            }
        }
        list_menu_pesanan_edit.setModel(ListModel);
    }//GEN-LAST:event_tombol_hapus_menu_pesanan_editMouseClicked

    private void tombol_hapus_menu_pesananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_hapus_menu_pesananMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tombol_hapus_menu_pesananMouseEntered

    private void tombol_hapus_semua_menu_pesanan_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_hapus_semua_menu_pesanan_editMouseClicked
        // TODO add your handling code here:
        listModel = new DefaultListModel<Menu>();
        list_menu_pesanan_edit.setModel(listModel);
    }//GEN-LAST:event_tombol_hapus_semua_menu_pesanan_editMouseClicked

    private void tombol_simpan_pesanan_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_simpan_pesanan_editMouseClicked
        // TODO add your handling code here:
        Pesanan pesanan = Pesanan.find(pesanan_id);
        Object pelanggan = combo_box_pelanggan_pesanan_edit.getSelectedItem();
        String pelanggan_id = ((Pelanggan) pelanggan).getId();
        List<Menu> list_menu = new ArrayList<Menu>();
        for(int i = 0; i< list_menu_pesanan.getModel().getSize();i++){
            Object item = list_menu_pesanan.getModel().getElementAt(i);
            list_menu.add(((Menu) item));
        }
        
        String dateString = date_chooser_pesanan_edit.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("M/d/yy");
        LocalDate localDate = LocalDate.parse(dateString, formatter);
        System.out.println("Created At : "+localDate.toString());
        
        pesanan.update(pelanggan_id, list_menu, localDate.toString());
        
        updatePesananTable();

        frame_ubah_pesanan.setVisible(false);
        
    }//GEN-LAST:event_tombol_simpan_pesanan_editMouseClicked

    private void tombol_status_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_status_pesananMouseClicked
        // TODO add your handling code here:
        Pesanan pesanan = Pesanan.find(pesanan_id);
        if(pesanan.status != null && (pesanan.status).equalsIgnoreCase("selesai")){
            JOptionPane.showMessageDialog(null, "Pesanan selesai, tidak dapat diubah", "Info", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            dialog_pesanan_status.setVisible(true);
        }
    }//GEN-LAST:event_tombol_status_pesananMouseClicked

    private void tombol_tidak_dialog_status_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_tidak_dialog_status_pesananMouseClicked
        // TODO add your handling code here:
        dialog_pesanan_status.setVisible(false);
    }//GEN-LAST:event_tombol_tidak_dialog_status_pesananMouseClicked

    private void tombol_ya_dialog_status_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_ya_dialog_status_pesananMouseClicked
        // TODO add your handling code here:
        Pesanan pesanan = Pesanan.find(pesanan_id);
        pesanan.update("selesai");
        
        updatePesananTable();
        
        dialog_pesanan_status.setVisible(false);

    }//GEN-LAST:event_tombol_ya_dialog_status_pesananMouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        Pesanan pesanan = Pesanan.find(pesanan_id);
        if(pesanan.status != null && (pesanan.status).equalsIgnoreCase("selesai")){
            JOptionPane.showMessageDialog(null, "Pesanan selesai, tidak dapat diubah", "Info", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            pesanan.delete();
            updatePesananTable();
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void tombol_cari_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_cari_pesananMouseClicked
        // TODO add your handling code here:
        String cari = text_field_cari_pesanan.getText();
        List<Pesanan> list_pesanan = Pesanan.cari(cari);
        PesananModel = getPesananTableModel();
        for(Pesanan pesanan: list_pesanan){
            PesananModel.addRow(pesanan.toTableRow());
        }
        PesananTable.setModel(PesananModel);
    }//GEN-LAST:event_tombol_cari_pesananMouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
   
    private javax.swing.table.DefaultTableModel MenuModel = getMenuTableModel();
    private javax.swing.table.DefaultTableModel getMenuTableModel(){
        return new javax.swing.table.DefaultTableModel(new Object [][] {}, new String [] {"ID", "Nama", "Harga"}){
            boolean[] canEdit = new boolean[]{false, false, false};
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        };
    }
    
    private javax.swing.table.DefaultTableModel PelangganModel = getPelangganTableModel();
    private javax.swing.table.DefaultTableModel getPelangganTableModel(){
        return new javax.swing.table.DefaultTableModel(new Object [][] {}, new String [] {"ID", "Nama", "Nomor Telepon"}){
            boolean[] canEdit = new boolean[]{false, false, false};
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        };
    }
    
    private javax.swing.table.DefaultTableModel PesananModel = getPesananTableModel();
    private javax.swing.table.DefaultTableModel getPesananTableModel(){
        return new javax.swing.table.DefaultTableModel(new Object [][] {}, new String [] {"ID", "Pelanggan", "Nomor Telepon", "Menu", "Jumlah", "Total", "Alamat", "Status", "Tanggal Pesan", "Tanggal Selesai"}){
            boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false, false, false, false};
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        };
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JTable MenuTable;
    private javax.swing.JPanel PelangganPanel;
    private javax.swing.JTable PelangganTable;
    private javax.swing.JPanel PesananPanel;
    private javax.swing.JTable PesananTable;
    private javax.swing.JComboBox<Menu> combo_box_menu_pesanan;
    private javax.swing.JComboBox<Menu> combo_box_menu_pesanan_edit;
    private javax.swing.JComboBox<Pelanggan> combo_box_pelanggan_pesanan;
    private javax.swing.JComboBox<Pelanggan> combo_box_pelanggan_pesanan_edit;
    private datechooser.beans.DateChooserCombo date_chooser_pesanan_edit;
    private datechooser.beans.DateChooserCombo date_chooser_tambah_pesanan;
    private javax.swing.JFrame dialog_pesanan_status;
    private javax.swing.JFrame frame_tambah_pesanan;
    private javax.swing.JFrame frame_ubah_pesanan;
    private javax.swing.JFrame frame_view_pesanan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList<Menu> list_menu_pesanan;
    private javax.swing.JList<Menu> list_menu_pesanan_edit;
    private javax.swing.JList<Menu> list_menu_view_pesanan;
    private javax.swing.JButton tambah_menu_pesanan;
    private javax.swing.JTextField text_field_cari;
    private javax.swing.JTextField text_field_cari_pesanan;
    private javax.swing.JTextField text_field_harga;
    private javax.swing.JTextField text_field_jumlah_menu_pesanan_edit;
    private javax.swing.JTextField text_field_nama;
    private javax.swing.JTextField text_field_pelanggan;
    private javax.swing.JTextField text_field_qty_menu_pesanan;
    private javax.swing.JTextField text_field_subtotal_pesanan;
    private javax.swing.JButton tombol_cari_pesanan;
    private javax.swing.JButton tombol_hapus_menu_pesanan;
    private javax.swing.JButton tombol_hapus_menu_pesanan_edit;
    private javax.swing.JButton tombol_hapus_semua_menu_pesanan;
    private javax.swing.JButton tombol_hapus_semua_menu_pesanan_edit;
    private javax.swing.JButton tombol_show_frame_tambah_pesanan;
    private javax.swing.JButton tombol_simpan_menu_pesanan;
    private javax.swing.JButton tombol_simpan_pesanan_edit;
    private javax.swing.JButton tombol_status_pesanan;
    private javax.swing.JButton tombol_tambah_menu_pesanan_edit;
    private javax.swing.JButton tombol_tidak_dialog_status_pesanan;
    private javax.swing.JButton tombol_tutup_view_pesanan;
    private javax.swing.JButton tombol_ubah_pesanan;
    private javax.swing.JButton tombol_ya_dialog_status_pesanan;
    // End of variables declaration//GEN-END:variables
}

